### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by NKUShaw** [vsingh-group/LCODEC-deep-unlearning#1]
Traceback (most recent call last):
  File "kfac_scrub.py", line 382, in <module>
    scrubMany(args)
  File "kfac_scrub.py", line 280, in scrubMany
    foci_val, updatedSD, samplossbefore, samplossafter, gradnormbefore, gradnormafter = inp_perturb(model, scrub_dataset, criterion, args, optim, device, outString=outString)
  File "/home/bhui/ML/xiaoyang/NextStep/Pruning/LCODEC-deep-unlearning/scrub/scrub_tools.py", line 288, in inp_perturb
    delwt, vectPOld = getOldPandG(outString, params.train_epochs-2, model, slices_to_update, device)
  File "/home/bhui/ML/xiaoyang/NextStep/Pruning/LCODEC-deep-unlearning/scrub/grad_utils.py", line 52, in getOldPandG
    paramlist = torch.load(name)
  File "/home/bhui/miniconda3/envs/xy38/lib/python3.8/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/bhui/miniconda3/envs/xy38/lib/python3.8/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/bhui/miniconda3/envs/xy38/lib/python3.8/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/cifar10_ResNet18_epochs_10_lr_0.0001_wd_0.01_bs_128_optim_sgd_notransform_epoch_8_params.pt'

where can I get 
name = outString + '_epoch_'  + str(epoch) + "_params.pt"
paramlist = torch.load(name)
name = outString + '_epoch_'  + str(epoch) + "_grads.pt"
gradlist = torch.load(name)
these two files?

**Comment by sourav-roni** [comment]
Hi, 

These will be based on your previously trained models from which you want to scrub. You might have to adjust the path based on how you have saved these.
